<?php
declare(strict_types=1);

// Generated by BotHub Frontend Designer.
$bh->dashboard->sidebar->addItem([
    'label'   => 'Weather Plugin',
    'icon'    => 'layout',
    'route'   => '/dashboard/plugins/weather-plugin/config',
    'section' => 'PLUGINS',
    'order'   => 100,
]);

$bh->dashboard->page->register('config', [
    'title'  => 'Weather Plugin',
    'icon'   => 'layout',
    'render' => 'pages/config.php',
]);
