<?php
declare(strict_types=1);
// Generated by BotHub Frontend Designer.

// $context wird von PluginExtensionRunner injiziert (plugin-page.php) bzw. dashboard/config.php
$botId = (int)($context['botId'] ?? $_SESSION['current_bot_id'] ?? 0);
$db    = bh_db();
$csrf  = (string)($_SESSION['csrf_token'] ?? '');
echo '<link rel="stylesheet" href="/assets/css/components-base.css?v=' . filemtime(BH_ROOT . '/assets/css/components-base.css') . '">';
?>
<style>
.bh-module-row { border-bottom: 1px solid var(--border); transition: background var(--transition); }
.bh-module-row:last-child { border-bottom: none; }
.bh-module-row > div:first-child:hover { background: var(--bg-hover); }
.bh-toggle { position: relative; display: inline-flex; cursor: pointer; flex-shrink: 0; }
.bh-toggle input { position: absolute; opacity: 0; width: 0; height: 0; }
.bh-toggle-track { width: 36px; height: 20px; background: var(--border-bright); border-radius: 10px; transition: background .2s; display: flex; align-items: center; padding: 2px; }
.bh-toggle input:checked ~ .bh-toggle-track { background: var(--toggle-color, var(--accent)); }
.bh-toggle-thumb { width: 16px; height: 16px; background: #fff; border-radius: 50%; transition: transform .2s; box-shadow: 0 1px 3px rgba(0,0,0,.3); }
.bh-toggle input:checked ~ .bh-toggle-track .bh-toggle-thumb { transform: translateX(16px); }
</style>
<?php
?>
<div class="bh-card" style="margin-bottom:16px;"><div class="bh-card-header"><span class="bh-card-title">Commands</span></div><?php (function () use ($botId, $db) {
    $moduleKey = 'weather-plugin:weather';
    $enabled = true;
    $settings = [];
    if ($botId > 0) { try {
        $db->prepare("INSERT IGNORE INTO bot_module_states (bot_id, module_key, enabled) VALUES (?, ?, ?)")
           ->execute([$botId, $moduleKey, 1]);
        $st = $db->prepare("SELECT enabled, settings FROM bot_module_states WHERE bot_id = ? AND module_key = ? LIMIT 1");
        $st->execute([$botId, $moduleKey]);
        $row = $st->fetch(PDO::FETCH_ASSOC) ?: [];
        $enabled = (bool)($row["enabled"] ?? $enabled);
        $settings = json_decode((string)($row["settings"] ?? "{}"), true) ?: [];
    } catch (Throwable) {} }
    $hasPerms = !empty($settings["allowed_roles"]) || !empty($settings["banned_roles"])
             || !empty($settings["banned_channels"]) || !empty($settings["required_permissions"]);
    $e = fn($v) => htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
?>
<div class="bh-module-row"><div style="display:flex;align-items:center;gap:12px;padding:10px 16px;flex:1;min-width:0;">
  <div style="flex:1;overflow:hidden;"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">
    <code style="font-size:11px;color:var(--accent-bright);background:var(--bg-hover);padding:2px 7px;border-radius:var(--radius-sm);white-space:nowrap;flex-shrink:0;">/weather [ort]</code>
    <div style="font-size:13px;font-weight:600;color:<?= $enabled ? 'var(--text-primary)' : 'var(--text-muted)' ?>;" id="label-weather-plugin-weather">Wetter</div>
  </div><div style="font-size:11px;color:var(--text-muted);margin-top:2px;">Zeigt das aktuelle Wetter für einen Ort an. Ort ist optional wenn Standard-Ort gesetzt.</div></div>
  <button class="bh-perm-btn <?= $hasPerms ? 'has-perms' : '' ?>" title="Berechtigungen" onclick="bhTogglePerms('perm-weather-plugin-weather')">
    <svg viewBox="0 0 16 16" fill="currentColor" width="13" height="13"><path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/></svg>
  </button>
  <label class="bh-toggle" style="--toggle-color:var(--color-primary);">
    <input type="checkbox" class="bh-cmd-toggle" <?= $enabled ? 'checked' : '' ?> onchange="bhToggleMod('weather-plugin:weather', this.checked, this, true)">
    <span class="bh-toggle-track"><span class="bh-toggle-thumb"></span></span>
  </label>
</div>
<?php
  $permModuleKey = $moduleKey;
  $permPanelId = 'perm-weather-plugin-weather';
  $permCfg = $settings;
  $permDiscordPerms = array (
  'Administrator' => 'Administrator',
  'ManageGuild' => 'Server verwalten',
  'ManageRoles' => 'Rollen verwalten',
  'ManageChannels' => 'Kanäle verwalten',
  'KickMembers' => 'Mitglieder kicken',
  'BanMembers' => 'Mitglieder bannen',
  'ManageMessages' => 'Nachrichten verwalten',
  'ModerateMembers' => 'Mitglieder per Timeout sperren',
  'MuteMembers' => 'Mitglieder stummschalten (Voice)',
  'ViewAuditLog' => 'Audit-Log anzeigen',
  'ManageWebhooks' => 'Webhooks verwalten',
  'ManageThreads' => 'Threads verwalten',
  'SendMessages' => 'Nachrichten senden',
  'MentionEveryone' => 'Alle erwähnen',
);
  require BH_ROOT . "/assets/features/permissions-panel.php";
?>
</div>
<?php })(); ?>

</div>
<div class="bh-card" style="margin-bottom:16px;"><div class="bh-card-header"><span class="bh-card-title">OpenWeatherMap API</span></div><?php (function () use ($botId, $db) {
  $row = [];
  if ($botId > 0) { try {
    $cst = $db->prepare("SELECT client_id FROM bots WHERE id = ? LIMIT 1");
    $cst->execute([$botId]);
    $keyVal = (string)($cst->fetchColumn() ?: "");
    if ($keyVal !== "" && $keyVal !== 0) {
      $st = $db->prepare("SELECT `api_key`, `units`, `default_location` FROM plugin_weather_plugin_settings WHERE client_id = ? LIMIT 1");
      $st->execute([$keyVal]);
      $row = $st->fetch(PDO::FETCH_ASSOC) ?: [];
    }
  } catch (Throwable) {} }
  $e = fn($v) => htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
?>
<div id="stg-alert-81e648b8" class="bh-alert" style="display:none;margin-bottom:12px;"></div>
<div style="display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap;padding:12px 0;border-bottom:1px solid var(--border);">
  <div style="flex:1;min-width:160px;"><div class="bh-label">API-Key (openweathermap.org)</div></div>
  <div style="flex:2;min-width:220px;">
    <input type="password" id="stg-81e648b8-api_key" class="bh-input" style="width:100%;" value="<?= $e($row['api_key'] ?? '') ?>" autocomplete="off">
  </div></div>
<div style="display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap;padding:12px 0;border-bottom:1px solid var(--border);">
  <div style="flex:1;min-width:160px;"><div class="bh-label">Einheit</div></div>
  <div style="flex:2;min-width:220px;">
    <select id="stg-81e648b8-units" class="bh-input" style="width:100%;"><?php foreach (array (
  0 => 
  array (
    'value' => 'metric',
    'label' => '°C — Metric',
  ),
  1 => 
  array (
    'value' => 'imperial',
    'label' => '°F — Imperial',
  ),
) as $opt): ?><option value="<?= $e($opt['value']) ?>" <?= (($row['units'] ?? '') === $opt['value']) ? 'selected' : '' ?>><?= $e($opt['label']) ?></option><?php endforeach; ?></select>
  </div></div>
<div style="display:flex;gap:20px;align-items:flex-start;flex-wrap:wrap;padding:12px 0;border-bottom:1px solid var(--border);">
  <div style="flex:1;min-width:160px;"><div class="bh-label">Standard-Ort</div></div>
  <div style="flex:2;min-width:220px;">
    <input type="text" id="stg-81e648b8-default_location" class="bh-input" style="width:100%;" value="<?= $e($row['default_location'] ?? '') ?>" autocomplete="off">
  </div></div>
<div style="display:flex;justify-content:flex-end;margin-top:12px;">
  <button type="button" id="stg-save-81e648b8" class="bh-btn bh-btn-primary" onclick="bhDsgSaveSettings81e648b8()">Speichern</button>
</div>
<?php })(); ?>
<script>
function bhDsgSaveSettings81e648b8() {
  var fields = [{"col":"api_key","id":"stg-81e648b8-api_key"},{"col":"units","id":"stg-81e648b8-units"},{"col":"default_location","id":"stg-81e648b8-default_location"}];
  var btn = document.getElementById("stg-save-81e648b8");
  var alertEl = document.getElementById("stg-alert-81e648b8");
  var body = { csrf_token: (window.BH_CSRF || window.CSRF || "") };
  fields.forEach(function (f) { var el = document.getElementById(f.id); if (el) body[f.col] = el.value; });
  body.action = "save";
  if (btn) { btn.disabled = true; btn.textContent = "…"; }
  fetch("/api/v1/plugins/weather-plugin", { method: "POST", headers: {"Content-Type":"application/json"}, body: JSON.stringify(body) })
    .then(function (r) { return r.json(); })
    .then(function (d) {
      if (alertEl) {
        alertEl.className = "bh-alert " + (d.ok ? "bh-alert-ok" : "bh-alert-error");
        alertEl.textContent = d.ok ? "Gespeichert ✓" : (d.error || "Fehler");
        alertEl.style.display = "block";
        setTimeout(function () { alertEl.style.display = "none"; }, 3500);
      }
    })
    .catch(function (e) { if (alertEl) { alertEl.className = "bh-alert bh-alert-error"; alertEl.textContent = "Netzwerkfehler: " + e.message; alertEl.style.display = "block"; } })
    .finally(function () { if (btn) { btn.disabled = false; btn.textContent = "Speichern"; } });
}
</script>

</div>

<script>
if (!window.BH_CSRF)   window.BH_CSRF   = <?= json_encode($csrf) ?>;
if (!window.BH_BOT_ID) window.BH_BOT_ID = <?= (int)$botId ?>;
// bhTogglePerms/bhSavePerms kommen aus dem globalen bh-permissions.js
// (perm-panel Markup/IDs sind identisch zu allen anderen Modulen) — keine
// lokale Kopie hier, damit es einheitlich mit den restlichen Modulen bleibt.
</script>
